spring.application.name=world-collections-security
server.port=8080

##########################################################################
##Start DataBase
##########################################################################
##spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;trustServerCertificate=true
spring.r2dbc.url=r2dbc:sqlserver://192.168.18.74:1433/master?encrypt=false&trustServerCertificate=true
spring.r2dbc.username=sa
spring.r2dbc.password=Str0ngPassword!
spring.sql.init.mode=always

application.base-path.world-control-collections = http://localhost:8083/

